import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const resources = {
  en: {
    translation: {
      appName: 'Samaj Setu',
      appTagline: 'Community Networking & Welfare Platform',
      nav: {
        home: 'Home',
        directory: 'Directory',
        blood: 'Blood Bank',
        business: 'Business',
        profile: 'Profile',
      },
      home: {
        welcome: 'Jay Shree Krishna',
        welcomeSub: 'Connected with your roots & community',
        quickActions: 'Quick Services',
        directoryCardTitle: 'Family Directory',
        directoryCardDesc: 'Explore verified member profiles, Gotras & native villages.',
        bloodCardTitle: 'Emergency Blood Bank',
        bloodCardDesc: 'Find instant blood donors & request urgent blood units.',
        businessCardTitle: 'Business Network',
        businessCardDesc: 'Support community entrepreneurs & discover exclusive member offers.',
        announcements: 'Samaj Notice Board & Events',
        viewAll: 'View All',
        emergencySOS: 'Emergency Blood SOS',
        emergencySOSDesc: 'Request urgent blood units in 30 seconds',
        statsMembers: 'Active Members',
        statsDonors: 'Blood Donors',
        statsBusinesses: 'Businesses',
        statsHelped: 'Blood Units Donated',
        latestNews: 'Community Updates',
      },
      directory: {
        title: 'Community Directory',
        subtitle: 'Connect with family members across the globe',
        searchPlaceholder: 'Search by Name, Village, Gotra or City...',
        filterAll: 'All Gotras',
        filterVillage: 'Filter Village',
        filterBlood: 'Blood Group',
        membersFound: 'Members Found',
        viewDetails: 'View Family Details',
        call: 'Call',
        whatsapp: 'WhatsApp',
        nativeVillage: 'Native Village',
        currentCity: 'Current City',
        gotra: 'Gotra',
        occupation: 'Occupation',
        familyMembers: 'Family Members',
        addEntry: 'Add Family Entry',
        noResults: 'No members found matching your search criteria.',
        clearFilters: 'Clear Filters',
        verified: 'Verified Member',
      },
      blood: {
        title: 'Emergency Blood Bank',
        subtitle: 'Save a life within our community',
        requestEmergencyBtn: 'Post Urgent Requirement',
        iWantToDonate: 'Register as Donor',
        donorStatus: 'Donor Availability',
        available: 'Available to Donate',
        notAvailable: 'Currently Unavailable',
        donorsFound: 'Verified Donors',
        filterByGroup: 'Select Blood Group',
        lastDonation: 'Last Donated',
        donationsDone: 'Donations',
        emergencyReady: '24x7 Emergency Ready',
        urgentRequests: 'Active Urgent Blood Requests',
        needBlood: 'Urgent Blood Needed',
        units: 'Units',
        hospital: 'Hospital',
        patient: 'Patient',
        whatsappShare: 'Broadcast to WhatsApp Groups',
        callContact: 'Call Coordinator',
        noDonors: 'No donors registered for this blood group yet.',
        donorRegisteredSuccess: 'Thank you! You are registered as an active donor.',
      },
      business: {
        title: 'Business Network',
        subtitle: 'Promote, grow & support community businesses',
        searchPlaceholder: 'Search businesses, products or services...',
        registerBusiness: 'List My Business',
        categories: {
          all: 'All Categories',
          retail: 'Retail & Shops',
          services: 'Services & CA/Legal',
          manufacturing: 'Manufacturing',
          food: 'Food & Catering',
          healthcare: 'Healthcare & Pharma',
          education: 'Education & Coaching',
          it: 'IT & Digital',
          realestate: 'Real Estate & Build',
          textiles: 'Textiles & Garments',
          other: 'Other',
        },
        specialOffer: 'Samaj Special Offer',
        owner: 'Owner',
        established: 'Est.',
        contactBusiness: 'Contact Business',
        noBusinesses: 'No businesses found in this category.',
      },
      profile: {
        title: 'My Profile & Settings',
        subtitle: 'Manage your community identity and privacy',
        loginPrompt: 'Sign in to access personalized directory features',
        signIn: 'Sign In / Register',
        fullName: 'Full Name',
        email: 'Email Address',
        phone: 'Mobile Number',
        whatsapp: 'WhatsApp Number',
        gotra: 'Gotra',
        nativeVillage: 'Native Village (વતન)',
        currentCity: 'Current Residence City',
        bloodGroup: 'Blood Group',
        occupation: 'Profession / Occupation',
        bio: 'About You & Family',
        avatarUpload: 'Profile Picture (<100KB compressed)',
        saveChanges: 'Save Profile Changes',
        savedSuccess: 'Profile saved successfully!',
        privacySettings: 'Privacy Controls',
        showPhoneInDir: 'Show phone number in public directory',
        showWhatsappInDir: 'Show WhatsApp direct link',
        appLanguage: 'Language / ભાષા',
        pwaInstall: 'Install App on Phone',
        pwaInstallDesc: 'Add Samaj Setu to your home screen for fast native access.',
        installBtn: 'Install PWA App',
        supabaseConfig: 'Supabase Database Config',
        cloudinaryConfig: 'Cloudinary Image Storage',
        logout: 'Log Out',
        demoMode: 'Demo Storage Mode (Zero-cost local/cloud sync)',
      },
      auth: {
        login: 'Member Login',
        signup: 'New Member Registration',
        continueWithGoogle: 'Continue with Google',
        orEmail: 'Or continue with email',
        email: 'Email address',
        password: 'Password',
        forgotPassword: 'Forgot Password?',
        submitLogin: 'Log In',
        submitSignup: 'Create Free Account',
        switchSignup: "Don't have an account? Sign Up",
        switchLogin: 'Already have an account? Log In',
        guestLogin: 'Quick Demo Login (Explore App)',
        guestDisclaimer: 'Instant access with pre-filled demo profile',
      },
      common: {
        loading: 'Loading data...',
        save: 'Save',
        cancel: 'Cancel',
        close: 'Close',
        search: 'Search',
        filter: 'Filter',
        all: 'All',
        yes: 'Yes',
        no: 'No',
        share: 'Share',
        copied: 'Link copied!',
      },
    },
  },
  gu: {
    translation: {
      appName: 'સમાજ સેતુ',
      appTagline: 'સમાજ નેટવર્કિંગ અને સેવા મંચ',
      nav: {
        home: 'હોમ',
        directory: 'ડિરેક્ટરી',
        blood: 'રક્તદાન',
        business: 'વેપાર',
        profile: 'પ્રોફાઇલ',
      },
      home: {
        welcome: 'જય શ્રી કૃષ્ણ',
        welcomeSub: 'તમારા વતન અને સમાજ સાથે સતત જોડાયેલા રહો',
        quickActions: 'મુખ્ય સેવાઓ',
        directoryCardTitle: 'પરિવાર ડિરેક્ટરી',
        directoryCardDesc: 'સમાજના સભ્યો, ગોત્ર અને વતનની વિગતો જુઓ.',
        bloodCardTitle: 'ઇમરજન્સી બ્લડ બેંક',
        bloodCardDesc: 'જરૂરિયાતના સમયે રક્તદાતા શોધો અથવા રક્તની વિનંતી કરો.',
        businessCardTitle: 'સમાજ બિઝનેસ નેટવર્ક',
        businessCardDesc: 'સમાજના ઉદ્યોગસાહસિકોને સહકાર આપો અને સ્પેશિયલ ઑફર્સ મેળવો.',
        announcements: 'સમાજ નોટિસ બોર્ડ અને કાર્યક્રમો',
        viewAll: 'બધા જુઓ',
        emergencySOS: 'ઇમરજન્સી રક્ત સહાય',
        emergencySOSDesc: 'તાત્કાલિક લોહીની જરૂરિયાત માટે ૩૦ સેકન્ડમાં વિનંતી મોકલો',
        statsMembers: 'કુલ સભ્યો',
        statsDonors: 'રક્તદાતાઓ',
        statsBusinesses: 'નોંધાયેલા વેપાર',
        statsHelped: 'રક્ત યુનિટ સહાય',
        latestNews: 'તાજા સમાચારો',
      },
      directory: {
        title: 'પરિવાર ડિરેક્ટરી',
        subtitle: 'વિશ્વભરમાં વસતા આપણા સમાજના પરિવારો સાથે જોડાઓ',
        searchPlaceholder: 'નામ, વતન, ગોત્ર અથવા શહેરથી શોધો...',
        filterAll: 'બધા ગોત્ર',
        filterVillage: 'વતન પસંદ કરો',
        filterBlood: 'બ્લડ ગ્રુપ',
        membersFound: 'સભ્યો મળ્યા',
        viewDetails: 'પરિવારની સંપૂર્ણ વિગતો',
        call: 'કોલ કરો',
        whatsapp: 'વોટ્સએપ',
        nativeVillage: 'વતન',
        currentCity: 'હાલનું શહેર',
        gotra: 'ગોત્ર',
        occupation: 'વ્યવસાય',
        familyMembers: 'પરિવારના સભ્યો',
        addEntry: 'પરિવારની નોંધણી કરો',
        noResults: 'કોઈ પરિણામ મળ્યું નથી.',
        clearFilters: 'ફિલ્ટર હટાવો',
        verified: 'પ્રમાણિત સભ્ય',
      },
      blood: {
        title: 'ઇમરજન્સી રક્તદાન કેન્દ્ર',
        subtitle: 'આપણા સમાજમાં કોઈનું જીવન બચાવવામાં સહભાગી બનો',
        requestEmergencyBtn: 'ઇમરજન્સી રક્ત વિનંતી મૂકો',
        iWantToDonate: 'રક્તદાતા તરીકે નોંધણી કરો',
        donorStatus: 'રક્તદાનની ઉપલબ્ધતા',
        available: 'રક્તદાન માટે તૈયાર',
        notAvailable: 'હાલમાં ઉપલબ્ધ નથી',
        donorsFound: 'રક્તદાતાઓ મળ્યા',
        filterByGroup: 'બ્લડ ગ્રુપ પસંદ કરો',
        lastDonation: 'છેલ્લું રક્તદાન',
        donationsDone: 'વખત દાન આપ્યું',
        emergencyReady: '૨૪x૭ ઇમરજન્સી તૈયાર',
        urgentRequests: 'ચાલુ તાત્કાલિક રક્ત વિનંતીઓ',
        needBlood: 'તાત્કાલિક રક્તની જરૂર છે',
        units: 'બોટલ / યુનિટ',
        hospital: 'હોસ્પિટલ',
        patient: 'દર્દીનું નામ',
        whatsappShare: 'વોટ્સએપ ગ્રુપમાં શેર કરો',
        callContact: 'સંપર્ક વ્યક્તિને કોલ કરો',
        noDonors: 'આ બ્લડ ગ્રુપના કોઈ રક્તદાતા મળ્યા નથી.',
        donorRegisteredSuccess: 'ખૂબ ખૂબ આભાર! તમારી રક્તદાતા તરીકે નોંધણી થઈ ગઈ છે.',
      },
      business: {
        title: 'સમાજ બિઝનેસ નેટવર્ક',
        subtitle: 'સ્વદેશી અને સમાજના વેપારીઓને પ્રોત્સાહન આપો',
        searchPlaceholder: 'વેપારનું નામ, પ્રોડક્ટ કે સેવા શોધો...',
        registerBusiness: 'મારો વેપાર નોંધાવો',
        categories: {
          all: 'બધી શ્રેણીઓ',
          retail: 'દુકાન / રિટેલ',
          services: 'સેવાઓ અને કન્સલ્ટિંગ',
          manufacturing: 'ઉદ્યોગ / મેન્યુફેક્ચરિંગ',
          food: 'ખાનપાન અને કેટરર્સ',
          healthcare: 'તબીબી / મેડિકલ',
          education: 'શિક્ષણ અને ટ્યુશન',
          it: 'આઈટી / ડિજિટલ સેવાઓ',
          realestate: 'રિયલ એસ્ટેટ / બાંધકામ',
          textiles: 'કાપડ અને ગારમેન્ટ્સ',
          other: 'અન્ય',
        },
        specialOffer: 'સમાજ સભ્યો માટે વિશેષ છૂટ',
        owner: 'સંચાલક / માલિક',
        established: 'સ્થાપના વર્ષ',
        contactBusiness: 'વેપાર સંપર્ક',
        noBusinesses: 'આ કેટેગરીમાં કોઈ વેપાર મળ્યો નથી.',
      },
      profile: {
        title: 'મારી પ્રોફાઇલ અને સેટિંગ્સ',
        subtitle: 'તમારી ઓળખ અને ગોપનીયતા નિયંત્રણો',
        loginPrompt: 'વિગતવાર સેવાઓ માટે લોગિન કરો',
        signIn: 'સાઇન ઇન / રજીસ્ટ્રેશન',
        fullName: 'પૂરું નામ',
        email: 'ઈમેલ એડ્રેસ',
        phone: 'મોબાઇલ નંબર',
        whatsapp: 'વોટ્સએપ નંબર',
        gotra: 'ગોત્ર',
        nativeVillage: 'વતન (મૂળ ગામ)',
        currentCity: 'હાલનું રહેઠાણ શહેર',
        bloodGroup: 'બ્લડ ગ્રુપ',
        occupation: 'વ્યવસાય / ધંધો',
        bio: 'પરિચય / પરિવાર વિગત',
        avatarUpload: 'પ્રોફાઇલ ફોટો (<100KB કમ્પ્રેસ્ડ)',
        saveChanges: 'પ્રોફાઇલ સેવ કરો',
        savedSuccess: 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ!',
        privacySettings: 'ગોપનીયતા સેટિંગ્સ',
        showPhoneInDir: 'ડિરેક્ટરીમાં મોબાઈલ નંબર દર્શાવો',
        showWhatsappInDir: 'વોટ્સએપ સીધી લિંક દર્શાવો',
        appLanguage: 'ભાષા / Language',
        pwaInstall: 'મોબાઇલમાં એપ ઇન્સ્ટોલ કરો',
        pwaInstallDesc: 'ઝડપી ઉપયોગ માટે સમાજ સેતુ એપને હોમ સ્ક્રીન પર ઉમેરો.',
        installBtn: 'PWA એપ ઇન્સ્ટોલ કરો',
        supabaseConfig: 'Supabase ડેટાબેઝ સેટિંગ્સ',
        cloudinaryConfig: 'Cloudinary ઇમેજ સ્ટોરેજ',
        logout: 'લોગઆઉટ',
        demoMode: 'ડેમો સ્ટોરેજ મોડ (ઝીરો-કોસ્ટ લોકલ/ક્લાઉડ)',
      },
      auth: {
        login: 'સભ્ય લોગિન',
        signup: 'નવા સભ્યની નોંધણી',
        continueWithGoogle: 'Google વડે લોગિન કરો',
        orEmail: 'અથવા ઇમેલ દ્વારા આગળ વધો',
        email: 'ઇમેલ એડ્રેસ',
        password: 'પાસવર્ડ',
        forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
        submitLogin: 'લોગ ઇન',
        submitSignup: 'ખાતું બનાવો',
        switchSignup: 'ખાતું નથી? રજીસ્ટર કરો',
        switchLogin: 'પહેલેથી ખાતું છે? લોગિન કરો',
        guestLogin: 'ડેમો સભ્ય લોગિન (ત્વરિત જુઓ)',
        guestDisclaimer: 'તૈયાર ડેમો પ્રોફાઇલ સાથે સીધો પ્રવેશ',
      },
      common: {
        loading: 'માહિતી લોડ થઈ રહી છે...',
        save: 'સેવ કરો',
        cancel: 'રદ કરો',
        close: 'બંધ કરો',
        search: 'શોધો',
        filter: 'ફિલ્ટર',
        all: 'બધા',
        yes: 'હા',
        no: 'ના',
        share: 'શેર કરો',
        copied: 'લિંક કોપી થઈ!',
      },
    },
  },
};

const savedLanguage = typeof window !== 'undefined' ? localStorage.getItem('samaj_language') || 'gu' : 'gu';

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: savedLanguage,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
