import { DirectoryMember, BloodDonor, Business, Announcement, BloodRequest, Gotra } from '../types';

export const GOTRAS_LIST: Gotra[] = [
  'Kashyap (કશ્યપ)',
  'Vashistha (વશિષ્ઠ)',
  'Bharadwaj (ભારદ્વાજ)',
  'Gautam (ગૌતમ)',
  'Jamadagni (જમદગ્નિ)',
  'Vishwamitra (વિશ્વામિત્ર)',
  'Agastya (અગસ્ત્ય)',
  'Sandilya (શાંડિલ્ય)',
  'Parashar (પરાશર)',
  'Kaushik (કૌશિક)',
  'Harita (હરિતા)',
  'Garg (ગાર્ગ્ય)',
  'Atri (અત્રિ)',
  'Other (અન્ય)',
];

export const VILLAGES_LIST = [
  'Rajkot (રાજકોટ)',
  'Jamnagar (જામનગર)',
  'Surat (સુરત)',
  'Ahmedabad (અમદાવાદ)',
  'Junagadh (જૂનાગઢ)',
  'Bhavnagar (ભાવનગર)',
  'Gondal (ગોંડલ)',
  'Morbi (મોરબી)',
  'Bhuj - Kutch (ભુજ - કચ્છ)',
  'Amreli (અમરેલી)',
  'Porbandar (પોરબંદર)',
  'Vadodara (વડોદરા)',
  'Navsari (નવસારી)',
  'Surendranagar (સુરેન્દ્રનગર)',
  'Anand (આણંદ)',
];

export const INITIAL_DIRECTORY_MEMBERS: DirectoryMember[] = [
  {
    id: 'mem-1',
    fullName: 'Harshil J. Joshi',
    fullNameGu: 'હર્ષિલ જે. જોષી',
    gotra: 'Kashyap (કશ્યપ)',
    nativeVillage: 'Gondal (ગોંડલ)',
    currentCity: 'Ahmedabad (અમદાવાદ)',
    bloodGroup: 'O+',
    phone: '+919876543210',
    whatsapp: '+919876543210',
    occupation: 'Software Engineer & Tech Lead',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    familyCount: 4,
    isVerified: true,
    isDonor: true,
    bio: 'Founder of Samaj Tech Connect initiative. Dedicated to community digital upliftment.',
    address: 'B-402, Shivam Residency, Bodakdev, Ahmedabad',
    familyMembers: [
      { id: 'f-1', name: 'Jayantbhai Joshi', relation: 'Father (પિતા)', age: 62, bloodGroup: 'O+' },
      { id: 'f-2', name: 'Bhavnaben Joshi', relation: 'Mother (માતા)', age: 58, bloodGroup: 'B+' },
      { id: 'f-3', name: 'Pooja Joshi', relation: 'Wife (પત્ની)', age: 29, bloodGroup: 'A+' },
    ],
  },
  {
    id: 'mem-2',
    fullName: 'Bhavna K. Mehta',
    fullNameGu: 'ભાવના કે. મહેતા',
    gotra: 'Vashistha (વશિષ્ઠ)',
    nativeVillage: 'Rajkot (રાજકોટ)',
    currentCity: 'Rajkot (રાજકોટ)',
    bloodGroup: 'B+',
    phone: '+919825012345',
    whatsapp: '+919825012345',
    occupation: 'Chartered Accountant (CA)',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    familyCount: 3,
    isVerified: true,
    isDonor: true,
    bio: 'Financial consultant and active volunteer in community girls education fund.',
    address: '101, Tirupati Heights, Kalawad Road, Rajkot',
    familyMembers: [
      { id: 'f-4', name: 'Kamleshbhai Mehta', relation: 'Husband (પતિ)', age: 38, bloodGroup: 'B+' },
      { id: 'f-5', name: 'Aarav Mehta', relation: 'Son (પુત્ર)', age: 8, bloodGroup: 'O+' },
    ],
  },
  {
    id: 'mem-3',
    fullName: 'Rameshbhai D. Patel',
    fullNameGu: 'રમેશભાઈ ડી. પટેલ',
    gotra: 'Bharadwaj (ભારદ્વાજ)',
    nativeVillage: 'Surat (સુરત)',
    currentCity: 'Surat (સુરત)',
    bloodGroup: 'A+',
    phone: '+919898098765',
    whatsapp: '+919898098765',
    occupation: 'Textile Manufacturer & Exporter',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    familyCount: 5,
    isVerified: true,
    isDonor: false,
    bio: 'Owner of Shree Krishna Sarees. President of Surat Youth Samaj Mandal.',
    address: 'Plot 44, Ring Road Industrial Area, Surat',
    familyMembers: [
      { id: 'f-6', name: 'Gitaben Patel', relation: 'Wife (પત્ની)', age: 52, bloodGroup: 'A+' },
      { id: 'f-7', name: 'Krunal Patel', relation: 'Son (પુત્ર)', age: 26, bloodGroup: 'A+' },
      { id: 'f-8', name: 'Neha Patel', relation: 'Daughter-in-law (પુત્રવધૂ)', age: 24, bloodGroup: 'AB+' },
    ],
  },
  {
    id: 'mem-4',
    fullName: 'Dr. Chirag N. Trivedi',
    fullNameGu: 'ડો. ચિરાગ એન. ત્રિવેદી',
    gotra: 'Gautam (ગૌતમ)',
    nativeVillage: 'Jamnagar (જામનગર)',
    currentCity: 'Jamnagar (જામનગર)',
    bloodGroup: 'AB+',
    phone: '+919426211223',
    whatsapp: '+919426211223',
    occupation: 'Cardiologist & Physician (MD)',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80',
    familyCount: 4,
    isVerified: true,
    isDonor: true,
    bio: 'Providing free medical consultation to all registered community senior citizens every Sunday.',
    address: 'Shreeji Heart Clinic, Opp. Town Hall, Jamnagar',
    familyMembers: [
      { id: 'f-9', name: 'Dr. Radhika Trivedi', relation: 'Wife (પત્ની)', age: 41, bloodGroup: 'B+' },
    ],
  },
  {
    id: 'mem-5',
    fullName: 'Pravinbhai M. Dave',
    fullNameGu: 'પ્રવીણભાઈ એમ. દવે',
    gotra: 'Sandilya (શાંડિલ્ય)',
    nativeVillage: 'Junagadh (જૂનાગઢ)',
    currentCity: 'Vadodara (વડોદરા)',
    bloodGroup: 'O-',
    phone: '+919712345678',
    whatsapp: '+919712345678',
    occupation: 'Real Estate Developer & Architect',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    familyCount: 4,
    isVerified: true,
    isDonor: true,
    bio: 'Specialist in affordable sustainable housing. Active Blood Donor for rare O- group.',
    address: 'Dave Arcade, Alkapuri, Vadodara',
  },
  {
    id: 'mem-6',
    fullName: 'Aniket V. Bhatt',
    fullNameGu: 'અનિકેત વી. ભટ્ટ',
    gotra: 'Kaushik (કૌશિક)',
    nativeVillage: 'Bhavnagar (ભાવનગર)',
    currentCity: 'Bhavnagar (ભાવનગર)',
    bloodGroup: 'B-',
    phone: '+919909012345',
    whatsapp: '+919909012345',
    occupation: 'Diamond Merchant & Jewelry Designer',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
    familyCount: 3,
    isVerified: true,
    isDonor: true,
    bio: 'Proprietor at Bhatt Gems. Youth Wing Sports Coordinator.',
    address: 'Waghawadi Road, Bhavnagar',
  },
];

export const INITIAL_BLOOD_DONORS: BloodDonor[] = [
  {
    id: 'donor-1',
    fullName: 'Harshil J. Joshi',
    fullNameGu: 'હર્ષિલ જે. જોષી',
    bloodGroup: 'O+',
    currentCity: 'Ahmedabad (અમદાવાદ)',
    nativeVillage: 'Gondal (ગોંડલ)',
    phone: '+919876543210',
    whatsapp: '+919876543210',
    lastDonationDate: '2025-11-15',
    isAvailable: true,
    donationCount: 6,
    isEmergencyReady: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'donor-2',
    fullName: 'Pravinbhai M. Dave (Rare O-)',
    fullNameGu: 'પ્રવીણભાઈ એમ. દવે (દુર્લભ O-)',
    bloodGroup: 'O-',
    currentCity: 'Vadodara (વડોદરા)',
    nativeVillage: 'Junagadh (જૂનાગઢ)',
    phone: '+919712345678',
    whatsapp: '+919712345678',
    lastDonationDate: '2025-10-02',
    isAvailable: true,
    donationCount: 14,
    isEmergencyReady: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'donor-3',
    fullName: 'Bhavna K. Mehta',
    fullNameGu: 'ભાવના કે. મહેતા',
    bloodGroup: 'B+',
    currentCity: 'Rajkot (રાજકોટ)',
    nativeVillage: 'Rajkot (રાજકોટ)',
    phone: '+919825012345',
    whatsapp: '+919825012345',
    lastDonationDate: '2025-12-20',
    isAvailable: true,
    donationCount: 4,
    isEmergencyReady: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'donor-4',
    fullName: 'Aniket V. Bhatt',
    fullNameGu: 'અનિકેત વી. ભટ્ટ',
    bloodGroup: 'B-',
    currentCity: 'Bhavnagar (ભાવનગર)',
    nativeVillage: 'Bhavnagar (ભાવનગર)',
    phone: '+919909012345',
    whatsapp: '+919909012345',
    lastDonationDate: '2026-01-10',
    isAvailable: true,
    donationCount: 8,
    isEmergencyReady: true,
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'donor-5',
    fullName: 'Dr. Chirag N. Trivedi',
    fullNameGu: 'ડો. ચિરાગ એન. ત્રિવેદી',
    bloodGroup: 'AB+',
    currentCity: 'Jamnagar (જામનગર)',
    nativeVillage: 'Jamnagar (જામનગર)',
    phone: '+919426211223',
    whatsapp: '+919426211223',
    lastDonationDate: '2025-09-18',
    isAvailable: true,
    donationCount: 11,
    isEmergencyReady: true,
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80',
  },
  {
    id: 'donor-6',
    fullName: 'Mayurbhai J. Shukla',
    fullNameGu: 'મયુરભાઈ જે. શુક્લ',
    bloodGroup: 'A-',
    currentCity: 'Surat (સુરત)',
    nativeVillage: 'Morbi (મોરબી)',
    phone: '+919824455667',
    whatsapp: '+919824455667',
    lastDonationDate: '2025-08-30',
    isAvailable: true,
    donationCount: 5,
    isEmergencyReady: true,
  },
  {
    id: 'donor-7',
    fullName: 'Sanjaybhai R. Vyas',
    fullNameGu: 'સંજયભાઈ આર. વ્યાસ',
    bloodGroup: 'AB-',
    currentCity: 'Ahmedabad (અમદાવાદ)',
    nativeVillage: 'Bhuj - Kutch (ભુજ - કચ્છ)',
    phone: '+919725511223',
    whatsapp: '+919725511223',
    lastDonationDate: '2025-11-05',
    isAvailable: true,
    donationCount: 7,
    isEmergencyReady: true,
  },
];

export const INITIAL_BLOOD_REQUESTS: BloodRequest[] = [
  {
    id: 'req-1',
    patientName: 'Ramanbhai K. Joshi',
    bloodGroup: 'O-',
    unitsRequired: 2,
    hospitalName: 'Sterling Hospital',
    hospitalAddress: '150 Feet Ring Road, Rajkot',
    city: 'Rajkot (રાજકોટ)',
    contactName: 'Nilesh Joshi (Son)',
    contactPhone: '+919825099881',
    whatsapp: '+919825099881',
    urgency: 'critical',
    reason: 'Emergency Cardiac Surgery. Urgently need 2 units of O Negative.',
    createdAt: '2026-08-22T20:15:00Z',
    isFulfilled: false,
  },
  {
    id: 'req-2',
    patientName: 'Kavitaben Trivedi',
    bloodGroup: 'B+',
    unitsRequired: 1,
    hospitalName: 'Civil Hospital',
    hospitalAddress: 'Asarwa, Ahmedabad',
    city: 'Ahmedabad (અમદાવાદ)',
    contactName: 'Dipak Trivedi',
    contactPhone: '+919428877665',
    whatsapp: '+919428877665',
    urgency: 'high',
    reason: 'Maternity Delivery complication.',
    createdAt: '2026-08-22T18:30:00Z',
    isFulfilled: false,
  },
];

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'biz-1',
    name: 'Shree Radhe Textiles & Sarees',
    nameGu: 'શ્રી રાધે ટેક્સટાઇલ અને સાડી સેન્ટર',
    category: 'textiles',
    ownerName: 'Rameshbhai D. Patel',
    nativeVillage: 'Surat (સુરત)',
    city: 'Surat (સુરત)',
    address: 'Shop 108, Millennium Market, Ring Road, Surat',
    phone: '+919898098765',
    whatsapp: '+919898098765',
    website: 'https://radhetextiles.in',
    description: 'Wholesale & Retail pure silk, Bandhani, and designer wedding sarees.',
    descriptionGu: 'શુદ્ધ સિલ્ક, બાંધણી અને લગ્ન પ્રસંગ માટેની ડિઝાઇનર સાડીઓના હોલસેલ અને રિટેલ વેપારી.',
    specialOffer: 'Special 10% discount on all purchases for registered Samaj members!',
    specialOfferGu: 'સમાજના તમામ સભ્યો માટે ખરીદી પર ૧૦% વિશેષ છૂટ!',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    isVerified: true,
    establishedYear: 1998,
  },
  {
    id: 'biz-2',
    name: 'Bhavna Mehta & Associates (CA Firm)',
    nameGu: 'ભાવના મહેતા એન્ડ એસોસિએટ્સ (સીએ ફર્મ)',
    category: 'services',
    ownerName: 'Bhavna K. Mehta (CA)',
    nativeVillage: 'Rajkot (રાજકોટ)',
    city: 'Rajkot (રાજકોટ)',
    address: '404, Star Chamber, Harihar Chowk, Rajkot',
    phone: '+919825012345',
    whatsapp: '+919825012345',
    website: 'https://bhavnamehtaca.com',
    description: 'Income Tax, GST, Company Audits, Startup Advisory & Family Wealth planning.',
    descriptionGu: 'ઇન્કમટેક્સ, જીએસટી, ઓડિટ અને સમાજના યુવાનો માટે સ્ટાર્ટઅપ માર્ગદર્શન સેવા.',
    specialOffer: 'Free first financial consultation & 15% discount on ITR filing for Samaj members.',
    specialOfferGu: 'સમાજ સભ્યો માટે પ્રથમ કન્સલ્ટેશન મફત અને ITR ફાઇલિંગ પર ૧૫% ડિસ્કાઉન્ટ.',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=80',
    isVerified: true,
    establishedYear: 2012,
  },
  {
    id: 'biz-3',
    name: 'Bhatt Gems & Heritage Jewellers',
    nameGu: 'ભટ્ટ જેમ્સ એન્ડ હેરિટેજ જ્વેલર્સ',
    category: 'retail',
    ownerName: 'Aniket V. Bhatt',
    nativeVillage: 'Bhavnagar (ભાવનગર)',
    city: 'Bhavnagar (ભાવનગર)',
    address: 'Near Ghanti Stand, M.G. Road, Bhavnagar',
    phone: '+919909012345',
    whatsapp: '+919909012345',
    website: 'https://bhattjewels.com',
    description: 'BIS 916 Hallmarked Gold Jewellery, certified Diamonds & traditional Gujarati ornaments.',
    descriptionGu: 'હોલમાર્કડ શુદ્ધ સોનું, ડાયમંડ અને પરંપરાગત ગુજરાતી ઘરેણાંના વિશ્વસનીય ઉત્પાદક.',
    specialOffer: '0% Making Charge on Gold Coins & Flat 25% Off on Diamond making for Samaj marriages.',
    specialOfferGu: 'સમાજના લગ્ન પ્રસંગો માટે સોનાના સિક્કા પર ૦% ઘડામણ અને ડાયમંડ પર ૨૫% છૂટ.',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80',
    isVerified: true,
    establishedYear: 1985,
  },
  {
    id: 'biz-4',
    name: 'Shreeji Ayurvedic & Healthcare Mart',
    nameGu: 'શ્રીજી આયુર્વેદિક એન્ડ હેલ્થકેર માર્ટ',
    category: 'healthcare',
    ownerName: 'Dr. Chirag N. Trivedi',
    nativeVillage: 'Jamnagar (જામનગર)',
    city: 'Jamnagar (જામનગર)',
    address: 'Opp. Ayurveda University Gate, Jamnagar',
    phone: '+919426211223',
    whatsapp: '+919426211223',
    description: 'Authentic pure Jamnagar Ayurvedic herbs, herbal wellness products & organic oils.',
    descriptionGu: 'જામનગરની અસલ શુદ્ધ આયુર્વેદિક ઔષધિઓ, ઓર્ગેનિક તેલ અને પંચકર્મ પ્રોડક્ટ્સ.',
    specialOffer: 'Flat 12% off on all Ayurvedic tonics & supplements with Samaj membership ID.',
    specialOfferGu: 'સમાજ મેમ્બરશિપ આઈડી પર તમામ આયુર્વેદિક ઔષધો પર ફ્લેટ ૧૨% ડિસ્કાઉન્ટ.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80',
    isVerified: true,
    establishedYear: 2005,
  },
  {
    id: 'biz-5',
    name: 'Dev Digital & Cloud Solutions',
    nameGu: 'દેવ ડિજિટલ એન્ડ ક્લાઉડ સોલ્યુશન્સ',
    category: 'it',
    ownerName: 'Harshil J. Joshi',
    nativeVillage: 'Gondal (ગોંડલ)',
    city: 'Ahmedabad (અમદાવાદ)',
    address: '702, Dev Aurum, Prahladnagar, Ahmedabad',
    phone: '+919876543210',
    whatsapp: '+919876543210',
    website: 'https://devcloud.tech',
    description: 'Web & Mobile App Development, Cloud Architecture, eCommerce & SEO for local businesses.',
    descriptionGu: 'સમાજના વેપારીઓ માટે આધુનિક વેબસાઇટ, મોબાઇલ એપ્લિકેશન અને ઓનલાઇન બિલિંગ સોફ્ટવેર.',
    specialOffer: 'Free domain & 20% discount on website development for Samaj entrepreneurs.',
    specialOfferGu: 'સમાજના નવા ઉદ્યોગસાહસિકો માટે વેબસાઇટ ડેવલપમેન્ટ પર ૨૦% વિશેષ રાહત.',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    isVerified: true,
    establishedYear: 2019,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Grand Annual Samaj Sneha Milan & Saraswati Sanman Mahotsav 2026',
    titleGu: 'વાર્ષિક સ્નેહમિલન અને સરસ્વતી સન્માન સમારોહ ૨૦૨૬',
    description: 'Cordially inviting all community families for our annual gathering, cultural performance, and felicitation of 10th/12th/Graduation meritorious students.',
    descriptionGu: 'આપણા સમાજના તમામ પરિવારજનોને વાર્ષિક સ્નેહમિલન અને તેજસ્વી વિદ્યાર્થી સન્માન સમારોહમાં સહકુટુંબ પધારવા હાર્દિક આમંત્રણ છે.',
    date: 'Sunday, 15 March 2026 • 9:00 AM',
    location: 'Shree Krishna Samaj Bhavan, Gondal Road, Rajkot',
    category: 'event',
    isUrgent: false,
    organizer: 'Samaj Central Executive Committee (મધ્યસ્થ કારોબારી સમિતિ)',
    imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'ann-2',
    title: 'Mega Blood Donation & Free Health Screening Camp',
    titleGu: 'મહારક્તદાન કેમ્પ અને સર્વરોગ નિદાન શિબિર',
    description: 'Jointly organized with Red Cross Society. Target 200+ blood units. Free ECG, Blood Sugar, and Eye testing available for all registered elders.',
    descriptionGu: 'રેડક્રોસ સોસાયટીના સહયોગથી આયોજિત. તમામ વડીલો માટે મફત ઇસીજી, બ્લડ સુગર અને નેત્ર તપાસ.',
    date: 'Sunday, 29 March 2026 • 8:30 AM to 2:00 PM',
    location: 'Samaj Community Hall, Bodakdev, Ahmedabad',
    category: 'blood_camp',
    isUrgent: true,
    organizer: 'Samaj Youth & Medical Wing (યુવા અને તબીબી પાંખ)',
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'ann-3',
    title: 'Samaj Matrimonial Meet (યુવક-યુવતી પરિચય મેળો)',
    titleGu: 'અખિલ ગુજરાત યુવક-યુવતી પરિચય મેળો ૨૦૨૬',
    description: 'Registration open for all eligible bachelors and professionals. Special booklet with verified family bio-data will be distributed.',
    descriptionGu: 'લગ્નોત્સુક યુવક-યુવતીઓ માટે પરિચય મેળો. ડિરેક્ટરી પુસ્તિકાનું વિમોચન થશે. રજીસ્ટ્રેશન શરૂ છે.',
    date: 'Sunday, 12 April 2026 • 10:00 AM',
    location: 'Kutch Kadva Patidar Bhavan, Surat',
    category: 'matrimonial',
    isUrgent: false,
    organizer: 'Matrimonial Coordination Cell (પરિચય સમિતિ)',
    imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
  },
];
